// Copyright Valhalla 2.0. All Rights Reserved.
//
// Golden-file tests for the stat and damage port.
//
// The fixtures are generated from the running Valhalla 1.0 TypeScript, so these
// tests are the only thing that actually proves the C++ port agrees with the
// game it is replacing. Reading them is the point: if one fails, the C++ is
// wrong, not the fixture.
//
// Fixture location: <DataRoot>/../../tools/fixtures/stats_fixtures.json
// (i.e. the 1.0 repo's tools/fixtures directory, beside shared/data).
//
// Run from the editor's Session Frontend, or headless:
//   UnrealEditor-Cmd.exe <project>.uproject -ExecCmds="Automation RunTests Valhalla.; Quit" -unattended -nullrhi

#include "CoreMinimal.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "Dom/JsonObject.h"
#include "Misc/AutomationTest.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "ValhallaConstants.h"
#include "ValhallaDataSettings.h"
#include "ValhallaDataSubsystem.h"
#include "ValhallaStats.h"
#include "ValhallaTypes.h"

/**
 * Flags shared by every test here. Written as a macro rather than a typed
 * constant because IMPLEMENT_SIMPLE_AUTOMATION_TEST wants the expression
 * inline, and the flag type itself changed shape between engine versions.
 */
#define VALHALLA_TEST_FLAGS ( \
	EAutomationTestFlags::EditorContext \
	| EAutomationTestFlags::ClientContext \
	| EAutomationTestFlags::ServerContext \
	| EAutomationTestFlags::CommandletContext \
	| EAutomationTestFlags::ProductFilter)

namespace ValhallaTests
{
	/** Every comparison in this file uses the same tolerance. */
	static constexpr double Tolerance = 1e-6;

	/** The data root the tests read the real game data from. */
	static FString GetDataRoot()
	{
		if (const UValhallaDataSettings* Settings = UValhallaDataSettings::Get())
		{
			return Settings->GetResolvedDataRoot();
		}
		return UValhallaDataSettings::ResolveDataRoot(FString());
	}

	/** <DataRoot>/../../tools/fixtures/stats_fixtures.json, absolute. */
	static FString GetFixturePath()
	{
		const FString Combined = FPaths::Combine(GetDataRoot(), TEXT("../../tools/fixtures/stats_fixtures.json"));
		return FPaths::ConvertRelativePathToFull(Combined);
	}

	/**
	 * Load the fixture file.
	 *
	 * Returns an invalid pointer when the file is absent. The fixture is
	 * generated by a separate tool, so a missing file means "not generated yet"
	 * rather than "the port is broken": callers warn and skip instead of
	 * failing, and a present-but-malformed file is a hard error.
	 */
	static TSharedPtr<FJsonObject> LoadFixtures(FAutomationTestBase& Test, bool& bOutMissing)
	{
		bOutMissing = false;

		const FString Path = GetFixturePath();
		FString RawText;
		if (!FFileHelper::LoadFileToString(RawText, *Path))
		{
			bOutMissing = true;
			Test.AddWarning(FString::Printf(
				TEXT("Fixture file not found at '%s' — skipping. Generate it from the 1.0 repo before trusting this suite."),
				*Path));
			return nullptr;
		}

		TSharedPtr<FJsonObject> Root;
		const TSharedRef<TJsonReader<TCHAR>> Reader = TJsonReaderFactory<TCHAR>::Create(RawText);
		if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
		{
			Test.AddError(FString::Printf(TEXT("Fixture file '%s' is not valid JSON: %s"), *Path, *Reader->GetErrorMessage()));
			return nullptr;
		}

		return Root;
	}

	/** Fetch one fixture array. Missing or empty is an error — the file claimed to exist. */
	static const TArray<TSharedPtr<FJsonValue>>* GetCases(FAutomationTestBase& Test, const TSharedPtr<FJsonObject>& Root, const TCHAR* Key)
	{
		const TArray<TSharedPtr<FJsonValue>>* Cases = nullptr;
		if (!Root->TryGetArrayField(Key, Cases) || Cases == nullptr)
		{
			Test.AddError(FString::Printf(TEXT("Fixture file has no '%s' array."), Key));
			return nullptr;
		}
		if (Cases->Num() == 0)
		{
			Test.AddError(FString::Printf(TEXT("Fixture array '%s' is empty — nothing was verified."), Key));
			return nullptr;
		}
		return Cases;
	}

	/** Object accessor that reports which case index was malformed. */
	static const TSharedPtr<FJsonObject>* AsCase(FAutomationTestBase& Test, const TArray<TSharedPtr<FJsonValue>>& Cases, int32 Index, const TCHAR* Key)
	{
		const TSharedPtr<FJsonObject>* CaseObj = nullptr;
		if (!Cases[Index].IsValid() || !Cases[Index]->TryGetObject(CaseObj) || CaseObj == nullptr)
		{
			Test.AddError(FString::Printf(TEXT("%s[%d] is not an object."), Key, Index));
			return nullptr;
		}
		return CaseObj;
	}

	static double Num(const TSharedPtr<FJsonObject>& Obj, const TCHAR* Key, double Fallback = 0.0)
	{
		double Value = Fallback;
		Obj->TryGetNumberField(Key, Value);
		return Value;
	}

	static bool Flag(const TSharedPtr<FJsonObject>& Obj, const TCHAR* Key, bool Fallback = false)
	{
		bool Value = Fallback;
		Obj->TryGetBoolField(Key, Value);
		return Value;
	}

	/** Compare a float result against a fixture expectation, reporting both. */
	static void CheckNear(FAutomationTestBase& Test, const FString& Label, double Actual, double Expected)
	{
		if (FMath::Abs(Actual - Expected) > Tolerance)
		{
			Test.AddError(FString::Printf(TEXT("%s: expected %.10f, got %.10f (delta %.3e)."),
				*Label, Expected, Actual, Actual - Expected));
		}
	}

	/** Integers must match exactly — a rounding difference here is a real bug. */
	static void CheckExact(FAutomationTestBase& Test, const FString& Label, int32 Actual, int32 Expected)
	{
		if (Actual != Expected)
		{
			Test.AddError(FString::Printf(TEXT("%s: expected %d, got %d."), *Label, Expected, Actual));
		}
	}

	static void CheckBool(FAutomationTestBase& Test, const FString& Label, bool Actual, bool Expected)
	{
		if (Actual != Expected)
		{
			Test.AddError(FString::Printf(TEXT("%s: expected %s, got %s."),
				*Label,
				Expected ? TEXT("true") : TEXT("false"),
				Actual ? TEXT("true") : TEXT("false")));
		}
	}

	/** Load the real data tables once per test, without needing a world. */
	static bool LoadRealTables(FAutomationTestBase& Test, FValhallaDataTables& OutTables)
	{
		const FString Root = GetDataRoot();
		if (!UValhallaDataSubsystem::LoadTablesFromRoot(Root, OutTables))
		{
			Test.AddError(FString::Printf(TEXT("Could not load the Valhalla data from '%s'. Check the Valhalla Data project setting."), *Root));
			return false;
		}
		return true;
	}
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Stats.DerivedStats — computeDerivedStats (stats.ts:25)
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaDerivedStatsTest,
	"Valhalla.Core.Stats.DerivedStats",
	VALHALLA_TEST_FLAGS)

bool FValhallaDerivedStatsTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	bool bMissing = false;
	const TSharedPtr<FJsonObject> Fixtures = LoadFixtures(*this, bMissing);
	if (bMissing) { return true; }
	if (!Fixtures.IsValid()) { return false; }

	FValhallaDataTables Tables;
	if (!LoadRealTables(*this, Tables)) { return false; }

	const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("derivedStats"));
	if (Cases == nullptr) { return false; }

	for (int32 Index = 0; Index < Cases->Num(); ++Index)
	{
		const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("derivedStats"));
		if (CaseObj == nullptr) { continue; }

		FString ClassIdText;
		(*CaseObj)->TryGetStringField(TEXT("classId"), ClassIdText);
		const int32 Level = static_cast<int32>(Num(*CaseObj, TEXT("level"), 1.0));

		const FValhallaClassTemplate* ClassTemplate = Tables.Classes.Find(FName(*ClassIdText));
		if (ClassTemplate == nullptr)
		{
			AddError(FString::Printf(TEXT("derivedStats[%d]: unknown class '%s'."), Index, *ClassIdText));
			continue;
		}

		const TSharedPtr<FJsonObject>* ExpectedObj = nullptr;
		if (!(*CaseObj)->TryGetObjectField(TEXT("expected"), ExpectedObj) || ExpectedObj == nullptr)
		{
			AddError(FString::Printf(TEXT("derivedStats[%d]: no 'expected' object."), Index));
			continue;
		}

		// 1.0 quirk (fixtures README #5): computeDerivedStats() in stats.ts reads the
		// hardcoded CLASS_TEMPLATES, not classes.json, and the two have diverged on
		// baseSpeed only. The fixtures therefore carry the CLASS_TEMPLATES speed. 2.0
		// deliberately uses the JSON (editor-owned) value at runtime, so the test
		// substitutes the legacy speed here rather than weakening the assertion.
		static const TMap<FName, float> LegacyClassTemplateSpeed = {
			{ TEXT("warrior"), 144.f }, { TEXT("cleric"), 152.f }, { TEXT("ranger"), 184.f },
			{ TEXT("rogue"), 168.f },   { TEXT("shaman"), 152.f }, { TEXT("wizard"), 152.f },
		};
		FValhallaClassTemplate LegacyTemplate = *ClassTemplate;
		if (const float* LegacySpeed = LegacyClassTemplateSpeed.Find(FName(*ClassIdText)))
		{
			LegacyTemplate.BaseSpeed = *LegacySpeed;
		}
		const FValhallaResolvedStats Actual = Valhalla::Stats::ComputeDerivedStats(LegacyTemplate, Level);
		const FString Prefix = FString::Printf(TEXT("derivedStats[%d] %s L%d"), Index, *ClassIdText, Level);

		auto Field = [&](const TCHAR* JsonKey, float ActualValue)
		{
			double ExpectedValue = 0.0;
			if (!(*ExpectedObj)->TryGetNumberField(JsonKey, ExpectedValue))
			{
				AddError(FString::Printf(TEXT("%s: fixture is missing expected.%s."), *Prefix, JsonKey));
				return;
			}
			CheckNear(*this, FString::Printf(TEXT("%s.%s"), *Prefix, JsonKey), ActualValue, ExpectedValue);
		};

		Field(TEXT("hp"),              Actual.Hp);
		Field(TEXT("mana"),            Actual.Mana);
		Field(TEXT("strength"),        Actual.Strength);
		Field(TEXT("stamina"),         Actual.Stamina);
		Field(TEXT("dexterity"),       Actual.Dexterity);
		Field(TEXT("intelligence"),    Actual.Intelligence);
		Field(TEXT("wisdom"),          Actual.Wisdom);
		Field(TEXT("physicalResist"),  Actual.PhysicalResist);
		Field(TEXT("spellResist"),     Actual.SpellResist);
		Field(TEXT("critChance"),      Actual.CritChance);
		Field(TEXT("critDamage"),      Actual.CritDamage);
		Field(TEXT("physicalDefense"), Actual.PhysicalDefense);
		Field(TEXT("blockRating"),     Actual.BlockRating);
		Field(TEXT("dodgeRating"),     Actual.DodgeRating);
		Field(TEXT("maxHp"),           Actual.MaxHp);
		Field(TEXT("maxMana"),         Actual.MaxMana);
		Field(TEXT("maxEnergy"),       Actual.MaxEnergy);
		Field(TEXT("energyRegenRate"), Actual.EnergyRegenRate);
		Field(TEXT("manaRegenRate"),   Actual.ManaRegenRate);
		Field(TEXT("speed"),           Actual.Speed);
	}

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Stats.Damage — computePhysicalDamage / computeSpellDamage
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaDamageFormulaTest,
	"Valhalla.Core.Stats.Damage",
	VALHALLA_TEST_FLAGS)

bool FValhallaDamageFormulaTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	bool bMissing = false;
	const TSharedPtr<FJsonObject> Fixtures = LoadFixtures(*this, bMissing);
	if (bMissing) { return true; }
	if (!Fixtures.IsValid()) { return false; }

	// stats.ts:78 — physical
	if (const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("physicalDamage")))
	{
		for (int32 Index = 0; Index < Cases->Num(); ++Index)
		{
			const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("physicalDamage"));
			if (CaseObj == nullptr) { continue; }

			const double Base = Num(*CaseObj, TEXT("base"));
			const double Strength = Num(*CaseObj, TEXT("strength"));
			const double Expected = Num(*CaseObj, TEXT("expected"));

			CheckNear(*this,
				FString::Printf(TEXT("physicalDamage[%d] base=%g str=%g"), Index, Base, Strength),
				Valhalla::Stats::ComputePhysicalDamage(Base, Strength),
				Expected);
		}
	}

	// stats.ts:85 — spell
	if (const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("spellDamage")))
	{
		for (int32 Index = 0; Index < Cases->Num(); ++Index)
		{
			const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("spellDamage"));
			if (CaseObj == nullptr) { continue; }

			const double Base = Num(*CaseObj, TEXT("base"));
			const double Intelligence = Num(*CaseObj, TEXT("intelligence"));
			const double Expected = Num(*CaseObj, TEXT("expected"));

			CheckNear(*this,
				FString::Printf(TEXT("spellDamage[%d] base=%g int=%g"), Index, Base, Intelligence),
				Valhalla::Stats::ComputeSpellDamage(Base, Intelligence),
				Expected);
		}
	}

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Stats.Xp — xpRequiredForLevel (stats.ts:199)
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaXpTest,
	"Valhalla.Core.Stats.Xp",
	VALHALLA_TEST_FLAGS)

bool FValhallaXpTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	bool bMissing = false;
	const TSharedPtr<FJsonObject> Fixtures = LoadFixtures(*this, bMissing);
	if (bMissing) { return true; }
	if (!Fixtures.IsValid()) { return false; }

	const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("xpRequired"));
	if (Cases == nullptr) { return false; }

	for (int32 Index = 0; Index < Cases->Num(); ++Index)
	{
		const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("xpRequired"));
		if (CaseObj == nullptr) { continue; }

		const int32 Level = static_cast<int32>(Num(*CaseObj, TEXT("level"), 1.0));
		const double Actual = Valhalla::Stats::XpRequiredForLevel(Level);

		// JSON cannot carry Infinity, so a max-level fixture omits `expected`
		// or sets it to null; either way we just assert the C++ is infinite.
		double Expected = 0.0;
		if (!(*CaseObj)->TryGetNumberField(TEXT("expected"), Expected))
		{
			if (FMath::IsFinite(Actual))
			{
				AddError(FString::Printf(TEXT("xpRequired[%d] level=%d: expected infinity, got %.10f."), Index, Level, Actual));
			}
			continue;
		}

		// XP totals are whole numbers in 1.0, so require an exact integer match.
		CheckExact(*this,
			FString::Printf(TEXT("xpRequired[%d] level=%d"), Index, Level),
			static_cast<int32>(Actual),
			static_cast<int32>(Expected));
		CheckNear(*this,
			FString::Printf(TEXT("xpRequired[%d] level=%d (exact)"), Index, Level),
			Actual, Expected);
	}

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Stats.AutoAttack — computeAutoAttackSpeed (stats.ts:184)
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaAutoAttackTest,
	"Valhalla.Core.Stats.AutoAttack",
	VALHALLA_TEST_FLAGS)

bool FValhallaAutoAttackTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	bool bMissing = false;
	const TSharedPtr<FJsonObject> Fixtures = LoadFixtures(*this, bMissing);
	if (bMissing) { return true; }
	if (!Fixtures.IsValid()) { return false; }

	const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("autoAttackSpeed"));
	if (Cases == nullptr) { return false; }

	for (int32 Index = 0; Index < Cases->Num(); ++Index)
	{
		const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("autoAttackSpeed"));
		if (CaseObj == nullptr) { continue; }

		const double BaseMs = Num(*CaseObj, TEXT("baseMs"));
		const double Dexterity = Num(*CaseObj, TEXT("dexterity"));
		const double Expected = Num(*CaseObj, TEXT("expected"));

		CheckNear(*this,
			FString::Printf(TEXT("autoAttackSpeed[%d] base=%g dex=%g"), Index, BaseMs, Dexterity),
			Valhalla::Stats::ComputeAutoAttackSpeed(BaseMs, Dexterity),
			Expected);

		// computeFireCooldown shares the formula; if they ever diverge the port
		// has drifted from stats.ts:160.
		CheckNear(*this,
			FString::Printf(TEXT("fireCooldown[%d] base=%g dex=%g"), Index, BaseMs, Dexterity),
			Valhalla::Stats::ComputeFireCooldown(BaseMs, Dexterity),
			Expected);
	}

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Stats.Pipeline — applyStatDamage (CombatSystem.ts:343)
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaDamagePipelineTest,
	"Valhalla.Core.Stats.Pipeline",
	VALHALLA_TEST_FLAGS)

bool FValhallaDamagePipelineTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	bool bMissing = false;
	const TSharedPtr<FJsonObject> Fixtures = LoadFixtures(*this, bMissing);
	if (bMissing) { return true; }
	if (!Fixtures.IsValid()) { return false; }

	const TArray<TSharedPtr<FJsonValue>>* Cases = GetCases(*this, Fixtures, TEXT("damagePipeline"));
	if (Cases == nullptr) { return false; }

	for (int32 Index = 0; Index < Cases->Num(); ++Index)
	{
		const TSharedPtr<FJsonObject>* CaseObj = AsCase(*this, *Cases, Index, TEXT("damagePipeline"));
		if (CaseObj == nullptr) { continue; }

		const TSharedPtr<FJsonObject>* InputObj = nullptr;
		const TSharedPtr<FJsonObject>* RollsObj = nullptr;
		const TSharedPtr<FJsonObject>* ExpectedObj = nullptr;
		if (!(*CaseObj)->TryGetObjectField(TEXT("input"), InputObj) || InputObj == nullptr
			|| !(*CaseObj)->TryGetObjectField(TEXT("rolls"), RollsObj) || RollsObj == nullptr
			|| !(*CaseObj)->TryGetObjectField(TEXT("expected"), ExpectedObj) || ExpectedObj == nullptr)
		{
			AddError(FString::Printf(TEXT("damagePipeline[%d]: needs 'input', 'rolls' and 'expected' objects."), Index));
			continue;
		}

		FValhallaDamageInput Input;
		Input.RawDamage               = Num(*InputObj, TEXT("rawDamage"));
		Input.bIsMagical              = Flag(*InputObj, TEXT("isMagical"));
		Input.AttackerDexterity       = Num(*InputObj, TEXT("attackerDexterity"));
		Input.AttackerCritChance      = Num(*InputObj, TEXT("attackerCritChance"));
		Input.AttackerCritDamage      = Num(*InputObj, TEXT("attackerCritDamage"));
		Input.DefenderDodgeRating     = Num(*InputObj, TEXT("defenderDodgeRating"));
		Input.DefenderBlockRating     = Num(*InputObj, TEXT("defenderBlockRating"));
		Input.DefenderPhysicalDefense = Num(*InputObj, TEXT("defenderPhysicalDefense"));
		Input.DefenderSpellResist     = Num(*InputObj, TEXT("defenderSpellResist"));
		Input.DefenderShieldHp        = Num(*InputObj, TEXT("defenderShieldHp"));

		FValhallaDamageRolls Rolls;
		Rolls.Hit   = Num(*RollsObj, TEXT("hit"));
		Rolls.Dodge = Num(*RollsObj, TEXT("dodge"));
		Rolls.Crit  = Num(*RollsObj, TEXT("crit"));
		Rolls.Block = Num(*RollsObj, TEXT("block"));

		const FValhallaDamageResult Actual = Valhalla::Stats::ResolveDamage(Input, Rolls);
		const FString Prefix = FString::Printf(TEXT("damagePipeline[%d]"), Index);

		FString ExpectedOutcomeText;
		if ((*ExpectedObj)->TryGetStringField(TEXT("outcome"), ExpectedOutcomeText))
		{
			EValhallaDamageOutcome ExpectedOutcome = EValhallaDamageOutcome::Miss;
			if (!Valhalla::ParseDamageOutcome(ExpectedOutcomeText, ExpectedOutcome))
			{
				AddError(FString::Printf(TEXT("%s: fixture outcome '%s' is not one of hit/miss/dodge."), *Prefix, *ExpectedOutcomeText));
			}
			else if (Actual.Outcome != ExpectedOutcome)
			{
				AddError(FString::Printf(TEXT("%s.outcome: expected '%s', got '%s'."),
					*Prefix, *ExpectedOutcomeText, *Valhalla::DamageOutcomeToString(Actual.Outcome)));
			}
		}

		double ExpectedDamage = 0.0;
		if ((*ExpectedObj)->TryGetNumberField(TEXT("damage"), ExpectedDamage))
		{
			CheckExact(*this, Prefix + TEXT(".damage"), Actual.Damage, static_cast<int32>(ExpectedDamage));
		}

		bool ExpectedFlag = false;
		if ((*ExpectedObj)->TryGetBoolField(TEXT("crit"), ExpectedFlag))
		{
			CheckBool(*this, Prefix + TEXT(".crit"), Actual.bCrit, ExpectedFlag);
		}
		if ((*ExpectedObj)->TryGetBoolField(TEXT("blocked"), ExpectedFlag))
		{
			CheckBool(*this, Prefix + TEXT(".blocked"), Actual.bBlocked, ExpectedFlag);
		}

		double ExpectedAbsorbed = 0.0;
		if ((*ExpectedObj)->TryGetNumberField(TEXT("shieldAbsorbed"), ExpectedAbsorbed))
		{
			CheckExact(*this, Prefix + TEXT(".shieldAbsorbed"), Actual.ShieldAbsorbed, static_cast<int32>(ExpectedAbsorbed));
		}
	}

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Data.Loads — the JSON loader against the real 1.0 data
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaDataLoadsTest,
	"Valhalla.Core.Data.Loads",
	VALHALLA_TEST_FLAGS)

bool FValhallaDataLoadsTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	// Deliberately calls the static loader rather than spinning up a
	// UGameInstance: the parser must not need a world to be testable.
	FValhallaDataTables Tables;
	if (!LoadRealTables(*this, Tables))
	{
		return false;
	}

	// These counts are the 1.0 content as of the Phase 1a port. If content is
	// added in 1.0, update these numbers deliberately — do not delete the test.
	CheckExact(*this, TEXT("class count"), Tables.Classes.Num(), 6);
	CheckExact(*this, TEXT("skill count"), Tables.Skills.Num(), 41);
	CheckExact(*this, TEXT("item count"), Tables.Items.Num(), 31);
	CheckExact(*this, TEXT("zone count"), Tables.Zones.Num(), 4);

	// Spot-check that a record actually converted rather than being an empty
	// struct under the right key.
	if (const FValhallaClassTemplate* Warrior = Tables.Classes.Find(FName(TEXT("warrior"))))
	{
		TestEqual(TEXT("warrior name"), Warrior->Name, FString(TEXT("Warrior")));
		TestEqual(TEXT("warrior armor"), static_cast<int32>(Warrior->AllowedArmor), static_cast<int32>(EValhallaArmorType::Plate));
		TestFalse(TEXT("warrior does not use mana"), Warrior->bCanUseMana);
		CheckNear(*this, TEXT("warrior base hp"), Warrior->BaseStats.Hp, 150.0);
		CheckNear(*this, TEXT("warrior vision range"), Warrior->VisionRange, 1200.0);
	}
	if (const FValhallaClassTemplate* Ranger = Tables.Classes.Find(FName(TEXT("ranger"))))
	{
		// Proves the visionRange key is actually read, not defaulted.
		CheckNear(*this, TEXT("ranger vision range"), Ranger->VisionRange, 1800.0);
	}
	else
	{
		AddError(TEXT("classes.json has no 'warrior'."));
	}

	// `classId: null` must survive as NAME_None, not as the string "null".
	if (const FValhallaSkillTemplate* MeleeAttack = Tables.Skills.Find(FName(TEXT("melee_attack"))))
	{
		TestTrue(TEXT("melee_attack has no class (available to all)"), MeleeAttack->ClassId.IsNone());
		TestTrue(TEXT("melee_attack is an auto-attack"), MeleeAttack->bIsAutoAttack);
	}
	else
	{
		AddError(TEXT("skills.json has no 'melee_attack'."));
	}

	// The `[min, max]` tuple must land in two scalars.
	if (const FValhallaSkillTemplate* Fireball = Tables.Skills.Find(FName(TEXT("wizard_fireball"))))
	{
		TestTrue(TEXT("wizard_fireball has baseDamage"), Fireball->bHasBaseDamage);
		CheckNear(*this, TEXT("wizard_fireball baseDamage min"), Fireball->BaseDamageMin, 22.0);
		CheckNear(*this, TEXT("wizard_fireball baseDamage max"), Fireball->BaseDamageMax, 34.0);
	}
	else
	{
		AddError(TEXT("skills.json has no 'wizard_fireball'."));
	}

	// classSkills and classColors are sidecar maps, not record tables.
	TestTrue(TEXT("classSkills loaded for every class"), Tables.ClassSkills.Num() == Tables.Classes.Num());
	TestTrue(TEXT("warrior has skills"), Tables.ClassSkills.Contains(FName(TEXT("warrior"))));
	TestTrue(TEXT("classColors loaded"), Tables.ClassColors.Num() > 0);

	// ui-config.json is kept raw for Phase 8. B-07 step 4 left it three
	// sections (the HUD layout is WBP_GameHUD's); typed, all three are there.
	TestTrue(TEXT("ui-config loaded"), Tables.UiConfig.IsValid());
	if (Tables.UiConfig.IsValid())
	{
		for (const TCHAR* Section : { TEXT("chat"), TEXT("inventory"), TEXT("nameplates") })
		{
			TestTrue(*FString::Printf(TEXT("ui-config has '%s'"), Section), Tables.UiConfig->HasTypedField<EJson::Object>(Section));
		}
		TestFalse(TEXT("ui-config has no 'hud' (WBP_GameHUD owns the layout)"), Tables.UiConfig->HasField(TEXT("hud")));
	}
	TestTrue(TEXT("typed ui-config has all three sections"), Tables.UIConfigTyped.HasAllSections());

	return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Valhalla.Core.Data.StatBonusRates — every rate in items.json is a decimal
// ─────────────────────────────────────────────────────────────────────────────

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FValhallaDataStatBonusRatesTest,
	"Valhalla.Core.Data.StatBonusRates",
	VALHALLA_TEST_FLAGS)

bool FValhallaDataStatBonusRatesTest::RunTest(const FString& Parameters)
{
	using namespace ValhallaTests;

	FValhallaDataTables Tables;
	if (!LoadRealTables(*this, Tables))
	{
		return false;
	}

	// The rate fields of FValhallaStatBlock are 0-1 decimals (0.05 == 5%), and
	// equipment bonuses are summed straight into the resolved block. A whole
	// number here — 1.0 shipped shields with `blockRating: 3` — is a 300% rate
	// once summed. The flat ratings (resists, defense, attributes) are not
	// rates and are not checked.
	int32 Checked = 0;
	for (const TPair<FName, FValhallaItemTemplate>& Pair : Tables.Items)
	{
		const FValhallaStatBlock& S = Pair.Value.StatBonuses;
		struct FRate { const TCHAR* Key; float Value; };
		const FRate Rates[] = {
			{ TEXT("critChance"),  S.CritChance },
			{ TEXT("critDamage"),  S.CritDamage },
			{ TEXT("blockRating"), S.BlockRating },
			{ TEXT("dodgeRating"), S.DodgeRating },
		};
		for (const FRate& Rate : Rates)
		{
			++Checked;
			if (Rate.Value < 0.f || Rate.Value > 1.f)
			{
				AddError(FString::Printf(TEXT("items.json '%s' statBonuses.%s = %.4f is outside [0, 1] (rates are decimals: 0.05 == 5%%)."),
					*Pair.Key.ToString(), Rate.Key, Rate.Value));
			}
		}
	}
	TestTrue(TEXT("some items were checked"), Checked > 0);

	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
